name: Build and Publish to NuGet

on:
  push:
    branches:
      - main
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
            
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
 
      - name: Build project
        run: |
            dotnet build --configuration Release

      - name: Pack no-dep
        run: |
            dotnet pack -p:UseNuspec=true --configuration Release --no-restore

      - name: Publish to NuGet.org
        run: |
          for file in ./Output/*.nupkg; do
            dotnet nuget push "$file" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
          done
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
